[project]
name = "slor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask-session>=0.8.0",
    "flask>=3.0.3",
    "moviepy>=1.0.3",
    "pillow>=11.0.0",
    "shortuuid>=1.0.13",
]
